language: python
python:
  - 3.6
  - 3.7
before_install:
  - python --version
  - pip install -U pip
  - pip install coverage
  - pip install colorama

script:
  - cd tests
  - coverage run -m unittest tests_runner # run tests
